# Generated by Django 5.2.4 on 2025-08-19 22:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_course_description_course_image_alter_course_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_courses', through='user.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
