# Generated by Django 5.2.4 on 2025-07-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_firstname_customuser_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='LastName',
        ),
    ]
