# Generated by Django 5.2.4 on 2025-08-20 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_course_subscribers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='qcm',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='qcm',
            name='passing_score',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='qcm',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='qcm',
            name='time_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='locked_contents',
            field=models.ManyToManyField(blank=True, related_name='locked_for_users', to='user.coursecontent'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QCMCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_score', models.FloatField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('attempts_count', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.qcm')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subscription')),
            ],
            options={
                'unique_together': {('subscription', 'qcm')},
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='completed_qcms',
            field=models.ManyToManyField(blank=True, through='user.QCMCompletion', to='user.qcm'),
        ),
        migrations.CreateModel(
            name='QCMAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.IntegerField(default=0)),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='user.qcm')),
                ('selected_options', models.ManyToManyField(to='user.qcmoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcm_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'qcm', 'attempt_number')},
            },
        ),
    ]
