# Generated by Django 5.2.4 on 2025-08-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_subscription_unique_together_qcm_max_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_of_course',
            field=models.CharField(max_length=100),
        ),
    ]
