# Generated by Django 5.2.4 on 2025-08-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='departement',
            field=models.CharField(choices=[('F', 'FINANCE'), ('H', 'Human RESOURCES'), ('M', 'MARKETING'), ('O', 'OPERATIONS/PRODUCTION'), ('S', 'Sales')], default='F', max_length=20),
        ),
    ]
