# Generated by Django 5.2.4 on 2025-08-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_course_departement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='departement',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Privilege',
            new_name='privilege',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('F', 'FINANCE'), ('H', 'Human RESOURCES'), ('M', 'MARKETING'), ('O', 'OPERATIONS/PRODUCTION'), ('S', 'Sales')], default='F', max_length=20),
        ),
    ]
