# Generated by Django 5.2.4 on 2025-08-31 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_departement_course_department_and_more'),
    ]

    operations = [
    ]
