# Generated by Django 5.2.4 on 2025-09-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_privilege_to_privilege'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='completed_contents',
            field=models.ManyToManyField(blank=True, related_name='completed_by_users', to='user.coursecontent'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='progress_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
