# Generated by Django 5.2.4 on 2025-09-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_subscription_completed_contents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfcontent',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
