# Generated by Django 5.2.4 on 2025-09-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_pdfcontent_is_completed_videocontent_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfcontent',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
