# Generated by Django 5.2.4 on 2025-09-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_enrollment_contentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(0, 'Brouillon'), (1, 'Actif'), (2, 'Archivé')], default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Actif'), (2, 'Suspendu')], default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
