# Generated by Django 5.2.4 on 2025-09-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_course_status_customuser_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived')], default=1),
        ),
        migrations.AddField(
            model_name='module',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived')], default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived')], default=1),
        ),
    ]
