# Generated by Django 5.2.4 on 2025-09-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_coursecontent_status_module_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='status',
        ),
        migrations.RemoveField(
            model_name='module',
            name='status',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Actif'), (2, 'Suspendu')], default=1),
        ),
    ]
