# Generated by Django 5.2.4 on 2025-10-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_coursecontent_status_remove_module_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='status',
            field=models.IntegerField(choices=[(0, 'Brouillon'), (1, 'Actif'), (2, 'Archivé')], default=1),
        ),
        migrations.AddField(
            model_name='module',
            name='status',
            field=models.IntegerField(choices=[(0, 'Brouillon'), (1, 'Actif'), (2, 'Archivé')], default=0),
        ),
    ]
