# Generated by Django 5.2.4 on 2025-10-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_qcmoption_options_contenttype_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='average_rating',
            field=models.FloatField(default=0, verbose_name='Note moyenne'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='completed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de complétions'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='completion_rate',
            field=models.FloatField(default=0, verbose_name='Taux de complétion'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de vues'),
        ),
    ]
