# Generated by Django 5.2.4 on 2025-10-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_coursecontent_average_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='completed_count',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='completion_rate',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='views_count',
        ),
    ]
