# Generated by Django 5.2.4 on 2025-11-02 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_coursecontent_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcm',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='qcm',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcm',
            name='question_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice')], default='single', max_length=10),
        ),
        migrations.AlterField(
            model_name='qcmoption',
            name='qcm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='user.qcm'),
        ),
        migrations.CreateModel(
            name='QCMQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice')], default='single', max_length=10)),
                ('points', models.IntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='user.qcm')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='qcmoption',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='user.qcmquestion'),
        ),
    ]
