# Generated by Django 5.2.4 on 2025-11-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_qcm_title_alter_qcm_question_alter_qcm_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcm',
            name='points',
        ),
        migrations.RemoveField(
            model_name='qcm',
            name='question',
        ),
        migrations.RemoveField(
            model_name='qcm',
            name='question_type',
        ),
    ]
