# Generated by Django 5.2.4 on 2025-11-02 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_remove_qcm_points_remove_qcm_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcmoption',
            name='qcm',
        ),
        migrations.AlterField(
            model_name='qcm',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='qcmoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='user.qcmquestion'),
        ),
    ]
