# Generated by Django 5.2.4 on 2025-11-07 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_favoritecourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('course_activated', 'Course Activated'), ('module_activated', 'Module Activated'), ('content_activated', 'Content Activated'), ('qcm_result', 'QCM Result'), ('system', 'System Announcement'), ('message', 'New Message')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.coursecontent')),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.course')),
                ('related_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='user_notifi_user_id_c3061c_idx'), models.Index(fields=['created_at'], name='user_notifi_created_0d33b6_idx')],
            },
        ),
    ]
